<h2>List Items</h2>
<?php 
if (count($this->paginator)): ?>
<div id="records">
  <form method="post" action="<?php echo $this->url(array(), 'admin-catalog-delete'); ?>">
    <table>
      <tr>
        <td></td>    
        <td class="key">
          Item ID
        <!-- Up arrow '&uArr;' and down arrow '&dArr;' are used to set the sort direction -->
          <a href="<?php echo $this->url(array('sort' => 'id', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a> 
          <a href="<?php echo $this->url(array('sort' => 'id', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>        
        </td>
        <td class="key">
          title
          <a href="<?php echo $this->url(array('sort' => 'title', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a> 
          <a href="<?php echo $this->url(array('sort' => 'title', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>        
        </td>
        <td class="key">
          Denomination
          <a href="<?php echo $this->url(array('sort' => 'denomination', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a> 
          <a href="<?php echo $this->url(array('sort' => 'denomination', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>                
        </td>
        <td class="key">
          Country
          <!-- Should this be country.id? -->
          <a href="<?php echo $this->url(array('sort' => 'country', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a> 
          <a href="<?php echo $this->url(array('sort' => 'country', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>                
        </td>
        <td class="key">
          Grade
          <a href="<?php echo $this->url(array('sort' => 'grade', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a> 
          <a href="<?php echo $this->url(array('sort' => 'grade', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>                
        </td>
        <td class="key">
          Year
          <!-- Changed 'Year' to 'creationdate' -->
	  <a href="<?php echo $this->url(array('sort' => 'creationdate', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a> 
          <a href="<?php echo $this->url(array('sort' => 'creationdate', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>                
        </td>    
        <td></td>    
        <td></td>    
      </tr>
      <?php foreach ($this->paginator as $item):?>
      <tr>
        <td><input type="checkbox" name="ids[]" value="<?php echo $item->id; ?>" style="width:2px" /></td>
        <td><?php echo $this->escape($item->id); ?></td>
        <td><?php echo $this->escape($item->title); ?></td>
        <td><?php echo $this->escape(sprintf('%1.2f', $item->denomination)); ?></td>
        <td><?php echo $this->escape($item->country->name); ?></td>
        <td><?php echo $this->escape($item->grade); ?></td>
        <td><?php echo $this->escape($item->year); ?></td>    
        <td><a href="<?php echo $this->url(array('id' => $item->id), 'admin-catalog-display'); ?>">Display</a></td>    
        <td><a href="<?php echo $this->url(array('id' => $item->id), 'admin-catalog-update'); ?>">Update</a></td>    
      </tr>  
      <?php endforeach; ?>
      <tr>
        <td colspan="7"><input type="submit" name="submit" style="width:150px" value="Delete Selected" /></td>
        <td colspan="2"><a href="<?php echo $this->url(array(), 'admin-fulltext-index-create'); ?>">Update full-text indices</a></td>
      </tr>    
    </table>
  </form>
</div>
<?php $this->paginationControl($this->products,
                             'Sliding',
                             './admin-item/_pagination.phtml'); ?>
<?php else: ?>
No records found
<?php endif; ?>
