<?php
/*
 This layout was modeled after
 http://www.scribd.com/doc/52150420/Getting-Started-with-Zend-Framework
*/
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Square Stamp Trading');
// The DOCTYPE is set in application.ini
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
<!--
This was in Vikram's master.phtml. I don't know what it does.
    <base href="/" />
-->
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/master.css'); ?>
  </head>
  <body>
    <div id="header">
      <div id="logo">
        <img src="/images/logo.gif"   />
      </div>
    
      <div id="menu">
        <a href="<?php echo $this->url(array(), 'home'); ?>">HOME</a>
        <a href="<?php echo $this->url(array('page' => 'services'), 'static-content'); ?>">SERVICES</a>
        <a href="<?php echo $this->url(array('module' => 'catalog',
            'controller' => 'item', 'action' => 'search'), 'default', true); ?>">CATALOG</a>
        <a href="<?php echo $this->url(array(), 'contact'); ?>">Contact</a>
       </div>
    </div>
    
    <div id="content">
      <?php echo $this->layout()->content ?>
    </div>
    
    <div id="footer">
      <p>Created with <a href="http://framework.zend.com/">Zend Framework</a>. Licensed under <a href="http://www.creativecommons.org/">Creative Commons</a>.</p>
    </div>    
  </body>
</html>
