<h2>Search</h2>
<?php echo $this->form; ?>

<h2>Search Results</h2>
<p><?php echo count($this->results) ?> result(s) found.</p>

<?php if (count($this->results)):
    $x = 1;

    foreach($this->results as $r):
?>
<div>
 <?= $x ?>.
 <a href="<?= $this->url(array('id' => $this->escape($r['id'])), 'catalog-display'); ?>">
   <?= $this->escape($r['title']); ?>
   <?= '(' . $this->escape($r['year']) . ')'; ?>
 </a>
<?php if (!empty($r['description'])):  ?>
      
       <br /><?= $this->escape($r['description']); ?>
 
     <?php endif;  ?>
     <br />
     <strong>
     Grade:    
     <?= $this->escape($r['grade']); ?> |
     Country:  
     <?= $this->escape($r['country']['name']); ?> |
      Sale Price: $<?= sprintf('%0.2f', $this->escape($r['salepricemin'])); ?> to $<?= sprintf('%0.2f', $this->escape($r['salepricemax'])); ?> 
      </strong>
     </div>
     <br />
     <?php $x++; ?>
   <?php endforeach; ?>
<?php endif; ?>
<div>
<a href="<?= $this->url(array('module' => 'catalog', 'controller' => 'item', 'action' => 'create'), null, true); ?>">Add Item</a>         
</div>
